name: Flutter-App-Builder
on: push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: Compress-Archive -Path build\windows\x64\runner\Release\* -Destination build\windows\x64\runner\Release\ShowsFlix.zip
      - name: Create Windows Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/x64/runner/Release/ShowsFlix.zip"
          tag: v1.0${{github.run_number}}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: Create Android Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          allowUpdates: true
          tag: v1.0${{github.run_number}}
          token: ${{ secrets.GITHUB_TOKEN }}
